repos:
  - repo: local
    hooks:
      - id: poetry-export
        name: Export requirements from Poetry
        entry: |
          bash -c '. .venv/bin/activate && poetry export -f requirements.txt --without dev -o requirements.txt && poetry export -f requirements.txt --only dev -o requirements-dev.txt'
        language: system
        pass_filenames: false
